# GoReleaser configuration for JOG
# https://goreleaser.com/

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: jog
    main: ./cmd/jog
    binary: jog
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/kumasuke/jog/internal/cli.Version={{.Version}}
      - -X github.com/kumasuke/jog/internal/cli.Commit={{.ShortCommit}}

archives:
  - id: default
    formats:
      - tar.gz
      - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: kumasuke
    name: jog
  draft: false
  prerelease: auto
