package auth

import (
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
)

// TestSigV4Golden is a golden test that pins the SigV4 canonical request
// layout, query canonicalization, signing-key derivation, and signature
// calculation to EXTERNALLY-DERIVED expected values. It guards against future
// refactors silently breaking the happy-path signature math.
//
// Source of the expected values (NOT generated by this implementation):
//
//	AWS Signature Version 4 test suite ("aws-sig-v4-test-suite"), as vendored
//	in botocore:
//	  https://github.com/boto/botocore/tree/develop/tests/unit/auth/aws4_testsuite
//	For each case below, the canonical request comes from <case>.creq and the
//	expected signature from <case>.authz (the Signature= field).
//
// The fixed credential pair used by every vector in that suite is documented
// by AWS: access key "AKIDEXAMPLE", secret key
// "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY", region "us-east-1", service
// "service", request time "20150830T123600Z" (scope date "20150830").
//
// Asserting against these external vectors (rather than re-signing with the
// same code under test) is the whole point: if calculateSignature or the
// canonicalization ever drifts from the AWS algorithm, this test fails instead
// of silently agreeing with a shared bug.
//
// Each case is checked in two layers so a failure is localized:
//   - Layer 1: createCanonicalRequest output must equal <case>.creq verbatim
//     (catches URI / query / header rendering bugs).
//   - Layer 2: calculateSignature output must equal <case>.authz's signature
//     (catches signing-key / string-to-sign / HMAC bugs).
func TestSigV4Golden(t *testing.T) {
	const (
		accessKey = "AKIDEXAMPLE"
		secretKey = "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY"
		region    = "us-east-1"
		service   = "service"
		date      = "20150830"
		amzDate   = "20150830T123600Z"
		host      = "example.amazonaws.com"

		signedHeaders = "host;x-amz-date"

		// SHA-256 of the empty payload (GET with no body). The suite's .creq
		// files end with this digest, NOT "UNSIGNED-PAYLOAD"; we therefore set
		// the X-Amz-Content-SHA256 header so createCanonicalRequest emits it
		// instead of defaulting to UNSIGNED-PAYLOAD.
		emptyPayloadHash = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
	)

	cases := []struct {
		name string
		// rawURI is the request target (path + optional query) as sent on the
		// wire, mirroring the suite's .req request line.
		rawURI string
		// wantCanonicalQuery is the canonical query line that must appear in
		// the canonical request (line 3 of .creq).
		wantCanonicalQuery string
		// wantSignature is the Signature= value from .authz.
		wantSignature string
	}{
		{
			// Case "get-vanilla": GET / with no query string. Exercises the
			// base canonical layout and signing math.
			name:               "get-vanilla",
			rawURI:             "/",
			wantCanonicalQuery: "",
			wantSignature:      "5fa00fa31553b73ebf1942676e86291e8372ff2a2260956d9b8aae1d763fbf31",
		},
		{
			// Case "get-vanilla-query-order-key-case": two distinct keys sent
			// out of order (Param2 before Param1). Exercises query
			// canonicalization key sorting: the canonical query must be
			// "Param1=value1&Param2=value2" regardless of wire order.
			name:               "get-vanilla-query-order-key-case",
			rawURI:             "/?Param2=value2&Param1=value1",
			wantCanonicalQuery: "Param1=value1&Param2=value2",
			wantSignature:      "b97d918cfa904a5beff61c982a1b6f458b799221646efd99d3219ec94cdf2500",
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			req := httptest.NewRequest(http.MethodGet, tc.rawURI, nil)
			req.Host = host
			req.Header.Set("X-Amz-Date", amzDate)
			req.Header.Set("X-Amz-Content-SHA256", emptyPayloadHash)

			m := NewMiddleware(accessKey, secretKey)

			// Layer 1: canonical request must match <case>.creq verbatim.
			wantCanonical := strings.Join([]string{
				"GET",
				"/",
				tc.wantCanonicalQuery,
				"host:" + host,
				"x-amz-date:" + amzDate,
				"",
				signedHeaders,
				emptyPayloadHash,
			}, "\n")
			gotCanonical := m.createCanonicalRequest(req, signedHeaders)
			if gotCanonical != wantCanonical {
				t.Fatalf("canonical request mismatch (%s.creq)\n got: %q\nwant: %q", tc.name, gotCanonical, wantCanonical)
			}

			// Layer 2: full signature must equal the external expected value.
			gotSignature := m.calculateSignature(req, date, region, service, signedHeaders)
			if gotSignature != tc.wantSignature {
				t.Fatalf("signature mismatch (%s.authz)\n got: %s\nwant: %s", tc.name, gotSignature, tc.wantSignature)
			}
		})
	}
}

// TestSigV4CanonicalQuery_MultiValueSort pins the AWS rule that, when a single
// query key carries multiple values, the values are sorted by their
// PERCENT-ENCODED representation (not by their decoded form).
//
// Source of the expected value: this is the AWS-documented canonicalization
// rule ("the query string values must be sorted by their URI-encoded value"),
// applied by hand below — NOT a signature produced by this implementation, and
// NOT a tautological re-signing of crafted input. No signature is asserted for
// this case; only the canonical query ordering is checked, which is exactly the
// behaviour issue #65 targets.
//
// Why this specific input: the AWS test-suite's own multi-value vector
// (get-vanilla-query-order-value, Param1=value1/value2) cannot detect the bug,
// because "value1"/"value2" are unreserved and encode to themselves, so a
// decoded sort and an encoded sort yield the identical string. To force the two
// sort orders apart we need a value that percent-encodes to a byte that sorts
// BEFORE an unreserved byte: every "%XX" escape begins with '%' (0x25), which is
// below all unreserved bytes (>= 0x2D). Using values "@" and ".":
//   - decoded sort: '.'(0x2E) < '@'(0x40)            => ".", "@"
//   - encoded sort: "%40"(0x25...) < "."(0x2E)       => "@", "."   <- AWS-correct
//
// So the AWS-correct canonical query is "Param1=%40&Param1=." while the old
// decoded-sort implementation emits "Param1=.&Param1=%40".
func TestSigV4CanonicalQuery_MultiValueSort(t *testing.T) {
	m := NewMiddleware("AKIDEXAMPLE", "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY")

	// Wire order deliberately differs from both sort orders so the test cannot
	// pass by accident of insertion order.
	req := httptest.NewRequest(http.MethodGet, "/?Param1=@&Param1=.", nil)

	const want = "Param1=%40&Param1=."
	got := m.canonicalQueryString(req)
	if got != want {
		t.Fatalf("multi-value canonical query mismatch\n got: %q\nwant: %q\n(values must be sorted by percent-encoded representation, per AWS SigV4)", got, want)
	}
}
